### ISSUE TITLE
can you animate the blur?

### ISSUE THREAD

**Issue by faceyspacey** [gre/gl-react-blur#2]

**Comment by gre** [comment]
Any React animation library should work with gl-react & it's beyond gl-react scope for you to choose the way you want to animate.

For instance we have examples using `react-motion` [here](http://projectseptemberinc.github.io/gl-react-dom/Examples/SpringCursor/) and [here](http://greweb.me/gl-react-dom-static-container/example/).
You might not even need an animation library and can do it yourself if you prefer, see for instance [this example](http://projectseptemberinc.github.io/gl-react-dom/Examples/AdvancedEffects/) (which is just about doing a render loop with `requestAnimationFrame`).
